---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nic
  namespace: mighty-gannet
spec:
  project: default
  source:
    path: charts/nginx-plus-ingress
    repoURL: https://github.com/charding2008/techxchange-gitops-lab.git
    targetRevision: HEAD
  destination:
    namespace: mighty-gannet
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
